import { Place } from '@/types';

export const mockPlaces: Place[] = [
  {
    id: '1',
    name: 'المسجد النبوي الشريف',
    description: 'المسجد النبوي هو مسجد النبي محمد صلى الله عليه وسلم، وهو ثاني أقدس مكان في الإسلام بعد المسجد الحرام في مكة المكرمة. يقع في المدينة المنورة ويحتوي على قبر النبي محمد صلى الله عليه وسلم.',
    type: 'religious',
    audience: ['family', 'seniors', 'friends'],
    environment: 'mixed',
    requiresBooking: false,
    reservationPrice: 0, // Free entry
    bookingsCount: 15000000,
    openingHours: 'مفتوح على مدار الساعة (مع أوقات محددة للنساء)',
    crowdLevel: 'high',
    currentEvents: ['صلاة التراويح في رمضان', 'دروس علمية يومية'],
    images: [
      'https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?w=800',
      'https://images.unsplash.com/photo-1580418827493-f2b22c0a76cb?w=800',
    ],
    latitude: 24.4672,
    longitude: 39.6111,
  },
  {
    id: '2',
    name: 'مسجد قباء',
    description: 'أول مسجد بني في الإسلام، وقد أسسه النبي محمد صلى الله عليه وسلم عندما هاجر من مكة إلى المدينة. الصلاة فيه تعدل عمرة.',
    type: 'religious',
    audience: ['family', 'seniors', 'friends'],
    environment: 'outdoor',
    requiresBooking: false,
    reservationPrice: 0, // Free entry
    bookingsCount: 5000000,
    openingHours: 'من الفجر حتى العشاء',
    crowdLevel: 'medium',
    currentEvents: ['دروس أسبوعية', 'برامج للأطفال خلال الإجازات'],
    images: [
      'https://images.unsplash.com/photo-1564769625905-50e93615e769?w=800',
    ],
    latitude: 24.4392,
    longitude: 39.6173,
  },
  {
    id: '3',
    name: 'جبل أحد',
    description: 'موقع معركة أحد التاريخية، وهو جبل يقع شمال المدينة المنورة. قال عنه النبي صلى الله عليه وسلم: "هذا جبل يحبنا ونحبه".',
    type: 'historical',
    audience: ['family', 'friends', 'seniors'],
    environment: 'outdoor',
    requiresBooking: false,
    reservationPrice: 0, // Free entry
    bookingsCount: 2500000,
    openingHours: 'مفتوح على مدار الساعة',
    crowdLevel: 'low',
    currentEvents: [],
    images: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    ],
    latitude: 24.4967,
    longitude: 39.6189,
  },
  {
    id: '4',
    name: 'متحف دار المدينة',
    description: 'متحف يعرض تاريخ المدينة المنورة وسيرة النبي محمد صلى الله عليه وسلم من خلال مجموعة من القطع الأثرية والمخطوطات والصور النادرة.',
    type: 'historical',
    audience: ['family', 'kids', 'friends'],
    environment: 'indoor',
    requiresBooking: true,
    reservationPrice: 30,
    bookingsCount: 450000,
    openingHours: 'السبت - الخميس: 9 صباحاً - 12 ظهراً، 5 - 9 مساءً',
    crowdLevel: 'medium',
    currentEvents: ['معرض خاص عن الهجرة النبوية'],
    images: [
      'https://images.unsplash.com/photo-1565099824688-e93eb20fe622?w=800',
    ],
    latitude: 24.4706,
    longitude: 39.6086,
  },
  {
    id: '5',
    name: 'مجمع الملك فهد لطباعة المصحف الشريف',
    description: 'أكبر مطبعة للقرآن الكريم في العالم، يمكن للزوار التعرف على مراحل طباعة المصحف ومشاهدة المعارض التعريفية.',
    type: 'religious',
    audience: ['family', 'kids', 'friends', 'seniors'],
    environment: 'indoor',
    requiresBooking: true,
    reservationPrice: 0, // Free but requires booking
    bookingsCount: 800000,
    openingHours: 'الأحد - الخميس: 8 صباحاً - 2 ظهراً',
    crowdLevel: 'low',
    currentEvents: ['جولات تعريفية مجانية'],
    images: [
      'https://images.unsplash.com/photo-1542816417-0983c9c9ad53?w=800',
    ],
    latitude: 24.4458,
    longitude: 39.5775,
  },
  {
    id: '6',
    name: 'حديقة الملك فهد المركزية',
    description: 'حديقة كبيرة مجهزة بمرافق ترفيهية للعائلات، مساحات خضراء واسعة، ومناطق ألعاب للأطفال.',
    type: 'entertainment',
    audience: ['family', 'kids'],
    environment: 'outdoor',
    requiresBooking: false,
    reservationPrice: 0,
    bookingsCount: 1200000,
    openingHours: '4 عصراً - 12 منتصف الليل',
    crowdLevel: 'high',
    currentEvents: ['فعاليات ترفيهية خلال الإجازات'],
    images: [
      'https://images.unsplash.com/photo-1588392382834-a891154bca4d?w=800',
    ],
    latitude: 24.4826,
    longitude: 39.5790,
  },
  {
    id: '7',
    name: 'النخيل مول',
    description: 'مركز تسوق حديث يضم العديد من المتاجر العالمية والمحلية، مطاعم متنوعة، وصالات سينما.',
    type: 'entertainment',
    audience: ['family', 'friends', 'kids'],
    environment: 'indoor',
    requiresBooking: false,
    reservationPrice: 0,
    bookingsCount: 3500000,
    openingHours: '9 صباحاً - 12 منتصف الليل',
    crowdLevel: 'high',
    currentEvents: ['تخفيضات الصيف', 'فعاليات ترفيهية نهاية الأسبوع'],
    images: [
      'https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?w=800',
    ],
    latitude: 24.4920,
    longitude: 39.5673,
  },
  {
    id: '8',
    name: 'متحف السيرة النبوية',
    description: 'متحف متخصص في عرض سيرة النبي محمد صلى الله عليه وسلم من خلال وسائل تفاعلية حديثة.',
    type: 'historical',
    audience: ['family', 'kids', 'friends', 'seniors'],
    environment: 'indoor',
    requiresBooking: false,
    reservationPrice: 0,
    bookingsCount: 600000,
    openingHours: 'السبت - الخميس: 8 صباحاً - 8 مساءً',
    crowdLevel: 'medium',
    currentEvents: [],
    images: [
      'https://images.unsplash.com/photo-1585060544812-6b45742d762f?w=800',
    ],
    latitude: 24.4693,
    longitude: 39.6120,
  },
  {
    id: '9',
    name: 'مزارع التمور',
    description: 'زيارة ميدانية لمزارع التمور الشهيرة في المدينة، مع إمكانية التعرف على أنواع التمور وطرق زراعتها.',
    type: 'entertainment',
    audience: ['family', 'kids', 'friends'],
    environment: 'outdoor',
    requiresBooking: true,
    reservationPrice: 50,
    bookingsCount: 180000,
    openingHours: '8 صباحاً - 4 عصراً',
    crowdLevel: 'low',
    currentEvents: ['موسم حصاد التمور (يوليو - سبتمبر)'],
    images: [
      'https://images.unsplash.com/photo-1587496679742-bad502958fbf?w=800',
    ],
    latitude: 24.5200,
    longitude: 39.5500,
  },
  {
    id: '10',
    name: 'البقيع',
    description: 'مقبرة البقيع هي المقبرة الرئيسية لأهل المدينة المنورة، ويوجد فيها قبور العديد من الصحابة وآل البيت.',
    type: 'religious',
    audience: ['family', 'seniors', 'friends'],
    environment: 'outdoor',
    requiresBooking: false,
    reservationPrice: 0,
    bookingsCount: 8000000,
    openingHours: 'بعد صلاة الفجر وبعد صلاة العصر',
    crowdLevel: 'medium',
    currentEvents: [],
    images: [
      'https://images.unsplash.com/photo-1590608032550-01bedc145a0a?w=800',
    ],
    latitude: 24.4675,
    longitude: 39.6145,
  },
];

